name: Deploy to production
on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone to vm
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup yarn
        uses: mskelton/setup-yarn@v1
        with:
          node-version: "16.x"
      - run: yarn install
      - name: Build and deploy
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          GH_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VITE_INIT_ADMIN_USER: ${{ secrets.VITE_INIT_ADMIN_USER }}
          VITE_CONTENTFUL_SPACE_ID: ${{ secrets.VITE_CONTENTFUL_SPACE_ID }}
          VITE_CONTENTFUL_CDA_TOKEN: ${{ secrets.VITE_CONTENTFUL_CDA_TOKEN }}
          VITE_CONTENTFUL_CPA_TOKEN: ${{ secrets.VITE_CONTENTFUL_CPA_TOKEN }}
        run: ./bin/deploy.sh
